export struct BookItem {
    saved: bool,
    title: string,
    author: string,

    description: string,

    book-url: string,
    chapter-urls: [string],
    chapter-durations: [string],
    chapter-reader: [string],
    image: image,
}

export component CoverImage inherits Rectangle {
    in-out property <image> src: @image-url("../img/republic2_1310.jpg");
    width: 250px;
    height: 250px;
    Rectangle {
        clip: true;
        border-radius: 5px;
        Image {
            width: 100%;
            height: 100%;
            image-fit: ImageFit.fill;
            source: src;
        }
    }
}
