import { Palette, HorizontalBox, ProgressIndicator, VerticalBox, Button, StandardButton } from "std-widgets.slint";
import { AudioState } from "playback.slint";

export component TopBar inherits Rectangle {
    in property <bool> compact;
    property <string> query;
    property <bool> search: false;

    HorizontalBox {
        padding: 7.5px;
        if AudioState.current-view != 0 && AudioState.current-view != 99: Rectangle {
            background: back_touch.pressed ? Palette.selection-background : Palette.alternate-background;
            padding: 10px;
            border-radius: 5px;
            width: 40px;
            height: 40px;
            Text {
                horizontal-alignment: TextHorizontalAlignment.left;
                text: "<";
                font-size: 25px;
                font-weight: 700;
            }
            back_touch := TouchArea {
                clicked => {
                    AudioState.go-to-previous-page();
                }
            }
        }
        
        if !search : Text {
            horizontal-alignment: TextHorizontalAlignment.left;
            text: AudioState.page-name;
            font-size: 25px;
            font-weight: 500;
            color: Palette.foreground;
        }

        if search : Rectangle {
            background: Palette.alternate-background;
            txtinpt := TextInput {
                color: Palette.foreground;
                font-size: 25px;
                vertical-alignment: center;
                single-line: true;
                init => {
                    self.select-all();
                }
                accepted => {
                    AudioState.on-search-clicked(self.text);
                    search = false;
                    AudioState.add-previous-page(AudioState.current-view);
                    AudioState.current-view = 1;
                    AudioState.page-name = "Search: " + self.text;
                }
            }
        }

        Image {
            horizontal-alignment: right;
            image-fit: ImageFit.contain;
            width: 40px;
            height: 40px;
            source: @image-url("../img/search-svgrepo-com.svg");

            touch := TouchArea {
                clicked => { 
                    search = !search;
                }
            }
            colorize: touch.pressed ? Palette.selection-background : Palette.foreground;
        }
    }}
export component NavBar inherits Rectangle {
    in property <bool> hidden;

    Rectangle {
        background: Palette.alternate-background;
        HorizontalBox {
            alignment: LayoutAlignment.center;
            spacing: 30px;
            Image {
                height: 50px;
                width: 50px;
                source: @image-url("../img/home-1-svgrepo-com.svg");
                colorize: touch1.pressed ? Palette.selection-background : Palette.foreground;
                touch1 := TouchArea {
                }
            }Image {
                    height: 50px;
                    width: 50px;
                    source: @image-url("../img/book-2-svgrepo-com.svg");
                    colorize: touch2.pressed ? Palette.selection-background : Palette.foreground;
                    touch2 := TouchArea {}
            }Image {
                    height: 50px;
                    width: 50px;
                    source: @image-url("../img/stack-apps-layers-svgrepo-com.svg");
                    colorize: touch3.pressed ? Palette.selection-background : Palette.foreground;
                    touch3 := TouchArea {}
            }Image {
                    height: 50px;
                    width: 50px;
                    source: @image-url("../img/settings-svgrepo-com.svg");
                    colorize: touch4.pressed ? Palette.selection-background : Palette.foreground;
                    touch4 := TouchArea {}
            }
        }
    }
}
