import { CoverImage } from "../components/book.slint";
import { AudioState } from "../components/playback.slint";
import { VerticalBox, ScrollView, HorizontalBox, Palette, Button } from "std-widgets.slint";

export component BookDetail inherits Rectangle {
    ScrollView {
        viewport-height: root.height * 1.5;
        if (AudioState.book-view.saved) : Rectangle {
            VerticalBox {
                spacing: 10px;
                CoverImage {
                    src: AudioState.book-view.image;
                }
                Text {
                    font-size: 20px;
                    font-weight: 500;
                    text: AudioState.book-view.title;
                    wrap: word-wrap;
                }
                Rectangle {
                    border-radius: 5px;
                    background: playNow.pressed ? Palette.selection-background : Palette.alternate-background;
                    Text {
                        text: "Download and play";
                    }
                    playNow := TouchArea {
                        clicked => { 
                            AudioState.chapter-download-and-play(AudioState.book-view.title, 0, AudioState.book-view.book-url);
                            AudioState.now-playing = AudioState.book-view;
                            AudioState.playing = true;
                         }
                    }
                }
            }
        }
        if (!AudioState.book-view.saved) : 
        Rectangle {
            VerticalBox {
                spacing: 10px;
                CoverImage {
                    src: AudioState.book-view.image;
                }
                Text {
                    font-size: 20px;
                    font-weight: 500;
                    text: AudioState.book-view.title;
                    wrap: word-wrap;
                }
                Rectangle {
                    border-radius: 5px;
                    background: downloadAll.pressed ? Palette.selection-background : Palette.alternate-background;
                    Text {
                        text: "Download";
                    }
                    downloadAll := TouchArea {
                        clicked => { 
                            AudioState.chapter-download(AudioState.book-view.title, 0, AudioState.book-view.book-url);
                         }
                    }
                }
                Rectangle {
                    border-radius: 5px;
                    background: downloadAll.pressed ? Palette.selection-background : Palette.alternate-background;
                    Text {
                        text: "Download and play";
                    }
                    DownloadAllAndPlay := TouchArea {
                        clicked => { 
                            AudioState.chapter-download-and-play(AudioState.book-view.title, 0, AudioState.book-view.book-url);
                            AudioState.now-playing = AudioState.book-view;
                            AudioState.playing = true;
                         }
                    }
                }
                for chapter[i] in AudioState.book-view.chapter-durations: Rectangle {
                    height: 25px;
                    background: download.pressed ? Palette.selection-foreground: Palette.alternate-background;
                    padding: 5px;
                    border-radius: 5px;
                    HorizontalBox {
                        padding: 0px;
                        spacing: 1px;
                        Rectangle {
                            height: 25px;
                            width: 25px;
                            Image {
                                height: 25px;
                                width: 25px;
                                source: @image-url("../img/download-svgrepo-com.svg");
                                colorize: download.pressed ? Palette.selection-foreground: Palette.alternate-foreground;
                            }
                            download := TouchArea {
                                clicked => {
                                    // downlaod the audio
                                    AudioState.chapter-download(AudioState.book-view.title, i, AudioState.book-view.chapter-urls[i]);
                                }
                            }
                        }
                        Text {
                            text: AudioState.book-view.chapter-durations[i];
                            font-size: 15px;
                        }
                        Text {
                            text: AudioState.book-view.chapter-reader[i];
                            font-size: 15px;
                        }
                        Rectangle {
                            height: 25px;
                            width: 25px;
                            Image {
                                height: 25px;
                                width: 25px;
                                source: @image-url("../img/play-svgrepo-com.svg");
                                colorize: play.pressed ? Palette.selection-foreground: Palette.alternate-foreground;

                            }
                            play := TouchArea {
                                clicked => {
                                    // downlaod the audio
                                    AudioState.chapter-download-and-play(AudioState.book-view.title, i, AudioState.book-view.chapter-urls[i]);
                                    AudioState.now-playing = AudioState.book-view;
                                    AudioState.playing = true;
                                }
                            }
                        }
                    }
                    
                }
            }
        }
    }
}