import { Button, VerticalBox, ScrollView, Palette ,ListView, HorizontalBox } from "std-widgets.slint";
import { AudioState } from "../components/playback.slint";

export component SearchDetail inherits Rectangle {
    for book[i] in AudioState.search-model: 
    Rectangle {
        
        x: root.width >= 750px 
        ? mod(i, max(1, floor((root.width - 350px)/170px))) * 165px + 5px
        : mod(i, max(1, floor(root.width/170px))) * 165px + 5px;

        y: root.width >= 750px 
        ? floor(i / floor((root.width - 350px)/170px)) * 220px
        : floor(i / floor(root.width/170px)) * 220px;
        
        width: 160px;
        height: 215px;                                

        border-radius: 15px;
        background: touch.pressed ? Palette.selection-background : Palette.alternate-background;
        VerticalBox {
            spacing: 2.5px;
            Image {
                source: book.image;
                horizontal-alignment: center;
                width: 125px;
                height: 125px;
            }
            Text {
                text: book.title;
                font-size: 15px;
                font-weight: 700;
                wrap: word-wrap;
                height: 50px;
            }
            Text {
                text: book.author;
            }
        }
        touch := TouchArea {
            clicked => {
                AudioState.on-book-view(book.book-url);
                AudioState.current-view = 5;
            }
        }
    }
}