import { Button, VerticalBox, ScrollView, Palette ,ListView, HorizontalBox, GridBox } from "std-widgets.slint";
import { AudioState } from "../components/playback.slint";

export component SearchDetail inherits Rectangle {
    property <length> item-width: 160px; 
    property <length> item-height: 215px;
    property <length> item-padding: 10px;
    property <int> libre-item-count: AudioState.search-libi.length;
    property <int> youtube-item-count: AudioState.search-yt.length;
    
    VerticalBox {
        Rectangle {
            height: item-height + 50px;
            width: root.width;
            VerticalBox {
                padding: 0px;
                Text{
                    text: "Libri";
                    font-size: 20px;
                }
                ScrollView {
                    viewport-width: (item-width + item-padding) * libre-item-count;
                    for book[i] in AudioState.search-libi: Rectangle {
                        x: i * (item-width + item-padding);
    
                        width: item-width;
                        height: item-height;                                
                        border-radius: 15px;
                        background: touch2.pressed ? Palette.selection-background : Palette.alternate-background;
                        
                        VerticalBox {
                            alignment: center;
                            spacing: 2.5px;
                            Image {
                                source: book.image;
                                horizontal-alignment: center;
                                width: 125px;
                                height: 125px;
                            }
                            Text {
                                text: book.title;
                                font-size: 15px;
                                font-weight: 700;
                                wrap: word-wrap;
                                height: 50px;
                            }
                            Text {
                                text: book.author;
                            }
                        }
                        touch2 := TouchArea {
                            clicked => {
                                AudioState.add-previous-page(AudioState.current-view);
                                AudioState.on-book-view(book.book-url);
                                AudioState.current-view = 5;
                            }
                        }
                    }
                }
            }
        }
        Rectangle {
            height: item-height + 50px;
            width: root.width;
            VerticalBox {
                padding: 0px;
                Text{
                    text: "Youtube";
                    font-size: 20px;
                }
                ScrollView {
                    viewport-width: (item-width + item-padding) * youtube-item-count;
                    for book[i] in AudioState.search-yt: Rectangle {
                        x: i * (item-width + item-padding);
    
                        width: item-width;
                        height: item-height;                                
                        border-radius: 15px;
                        background: touch3.pressed ? Palette.selection-background : Palette.alternate-background;
                        
                        VerticalBox {
                            alignment: center;
                            spacing: 2.5px;
                            Image {
                                source: book.image;
                                horizontal-alignment: center;
                                width: 125px;
                                height: 125px;
                            }
                            Text {
                                text: book.title;
                                font-size: 15px;
                                font-weight: 700;
                                wrap: word-wrap;
                                height: 50px;
                            }
                            Text {
                                text: book.author;
                            }
                        }
                        touch3 := TouchArea {
                            clicked => {
                                AudioState.on-book-view(book.book-url);
                                AudioState.add-previous-page(AudioState.current-view);
                                AudioState.current-view = 5;
                            }
                        }
                    }
                }
            }
        }
    }
}