import { Button, VerticalBox, ScrollView, Palette ,ListView, HorizontalBox } from "std-widgets.slint";
import { BookItem, CoverImage } from "components/book.slint";
import { PlayingBar, PlayingWindow, AudioState } from "components/playback.slint";
import { TopBar, NavBar } from "components/navigation.slint";
import { BookDetail } from "views/book.slint";
import { SearchDetail } from "views/search.slint";

export * from "components/playback.slint";
/*

    We want to have differnt sections:
        - Home page:
            - Continue listening,
            - Downloads,
            - Short lists,
            - Recemntly played
        - Search/discover
        - Books
        - Settings
            - Youtube login, drive login, download location
        - Now playing location
            - Volume
            - Night timer
            - Time left
            - Speed up/down
            - transcipt
        - Book view
        - Bookmarks
*/

// Should add rating too!
// Do some matching for the genres, and if it is a genre then return genres!

export component AppWindow inherits Window {
    title: "Audiody";
    background: Palette.background;
    
    min-width: 350px;
    min-height: 600px;
    HorizontalBox {
        padding: 0px;
        spacing: 0px;
        VerticalBox {
            padding: 0px;
            spacing: 0px;

            TopBar {
                height: 55px;
                compact: root.width >= 750px ? false : true;
            }

            Rectangle {
                // This is where the views will go!
                min-height: 200px;
                if AudioState.current-view == 5: BookDetail {}
                if AudioState.current-view == 1: SearchDetail {}
            }

            if root.width < 750px && AudioState.playing : Rectangle {
                height: 50px;
                // Placeholder for timebar
                // Placeholder for the time
                PlayingBar {
                    border-bottom-left-radius: 0px;
                    border-bottom-right-radius: 0px;
                }
            }
            NavBar {

            }
        }

        if root.width >= 750px && AudioState.playing : Rectangle {

            PlayingWindow {
                max-width: 350px;
            }
        }
    }
}
