import { Button, VerticalBox, ScrollView, Palette ,ListView, HorizontalBox } from "std-widgets.slint";
import { BookItem, CoverImage } from "components/book.slint";
import { PlayingBar, PlayingWindow, AudioState } from "components/playback.slint";
import { TopBar, NavBar } from "components/navigation.slint";

export * from "components/playback.slint";
/*

    We want to have differnt sections:
        - Home page:
            - Continue listening,
            - Downloads,
            - Short lists,
            - Recemntly played
        - Search/discover
        - Books
        - Settings
            - Youtube login, drive login, download location
        - Now playing location
            - Volume
            - Night timer
            - Time left
            - Speed up/down
            - transcipt
        - Book view
        - Bookmarks
*/

// Should add rating too!
// Do some matching for the genres, and if it is a genre then return genres!

export component AppWindow inherits Window {
    title: "Audiody";
    background: Palette.background;
    in-out property <[BookItem]> book-model: [];
    min-width: 350px;
    min-height: 600px;

    HorizontalBox {
        padding: 0px;
        spacing: 0px;
        VerticalBox {
            padding: 0px;
            spacing: 0px;

            TopBar {
                height: 55px;
                compact: root.width >= 750px ? false : true;
            }

            Rectangle {
                // This is where the views will go!
                min-height: 200px;
                ScrollView {
                    ListView {
                        for book in root.book-model: 
                        VerticalBox{
                            padding: 2.5px;
                            Rectangle {
                                width: 160px;
                                height: 215px;
                                border-radius: 15px;
                                background: touch.pressed ? Palette.selection-background : Palette.alternate-background;
                                VerticalBox {
                                    spacing: 2.5px;
                                    Image {
                                        source: book.image;
                                        horizontal-alignment: center;
                                        width: 125px;
                                        height: 125px;
                                    }
                                    Text {
                                        text: book.title;
                                        font-size: 15px;
                                        font-weight: 700;
                                        wrap: word-wrap;
                                        height: 50px;
                                    }
                                    Text {
                                        text: book.author;
                                    }
                                    
                                }
                                touch := TouchArea {
                                    clicked => {}
                                }
                            }
                        }
                    }
                }
            }

            if root.width < 750px && AudioState.playing : Rectangle {
                height: 50px;
                // Placeholder for timebar
                // Placeholder for the time
                PlayingBar {
                    border-bottom-left-radius: 0px;
                    border-bottom-right-radius: 0px;
                }
            }
            NavBar {

            }
        }

        if root.width >= 750px && AudioState.playing : Rectangle {

            PlayingWindow {
                max-width: 350px;
            }
        }
    }
}
